services:
  ai-agent:
    platform: linux/amd64
    build:
      context: .
    ports:
      - "8000:8000"  # FastAPI 모니터링 포트
    environment:
      # 실서버 설정
      # - BROKER_HOST=bell.softcloud.co.kr
      # - BROKER_PORT=25555
      
      # 로컬 테스트 설정
      - BROKER_HOST=broker  # localhost에서 broker 서비스 이름으로 변경
      - BROKER_PORT=5555
      - CLIENT_ID=AIAGNT  # AI 에이전트용 고유 ID (6자리 영문 대문자)
    env_file:
      - .env
    volumes:
      - .:/aiagent
    restart: always
    depends_on:  # broker 서비스가 시작된 후에 시작하도록 설정
      - broker

  # 로컬 테스트용 브로커 서버
  broker:
    platform: linux/amd64
    image: python:3.9-slim
    command: >
      sh -c "pip install -r /app/requirements.txt &&
             sh /app/start-broker.sh"
    ports:
      - "5555:5555"  # ZMQ 브로커 포트
    volumes:
      - ./brokerserver.py:/app/brokerserver.py
      - ./start-broker.sh:/app/start-broker.sh
      - ./requirements.txt:/app/requirements.txt
    working_dir: /app
    environment:
      - PYTHONUNBUFFERED=1
    restart: always
