# 실무용 Docker Compose
version: '3.8'

services:
  ai-agent:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: smartcast-aiagent-ai-agent
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - BROKER_HOST=broker
      - BROKER_PORT=5555
      - LOG_LEVEL=INFO
    volumes:
      - ./logs:/app/logs
    depends_on:
      - broker
    restart: unless-stopped
    networks:
      - aiagent-network

  broker:
    image: redis:7-alpine
    container_name: smartcast-aiagent-broker
    ports:
      - "5555:6379"
    restart: unless-stopped
    networks:
      - aiagent-network

networks:
  aiagent-network:
    driver: bridge

volumes:
  logs:
