services:
  ai-agent:
    platform: linux/amd64
    build:
      context: .
    ports:
      - "8000:8000"  # FastAPI 모니터링 포트
    environment:
      # 실서버 설정
      # - BROKER_HOST=bell.softcloud.co.kr
      # - BROKER_PORT=25555
      
      # 로컬 테스트 설정
      - BROKER_HOST=broker  # localhost에서 broker 서비스 이름으로 변경
      - BROKER_PORT=5555
      - CLIENT_ID=AIAGNT  # AI 에이전트용 고유 ID (6자리 영문 대문자)
      
      # 한국 시간대 설정
      - TZ=Asia/Seoul
    env_file:
      - .env
    volumes:
      - .:/aiagent
      # 시스템 시간대 파일 마운트 (추가 안정성)
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    restart: always
    depends_on:  # broker와 postgres 서비스가 시작된 후에 시작하도록 설정
      - broker
      - postgres

  # PostgreSQL 데이터베이스
  postgres:
    image: postgres:15-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=aiagent
      - POSTGRES_USER=aiagent
      - POSTGRES_PASSWORD=aiagent123
      - TZ=Asia/Seoul
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    restart: always

  # 로컬 테스트용 브로커 서버
  broker:
    platform: linux/amd64
    image: python:3.9-slim
    command: >
      sh -c "pip install -r /app/requirements.txt &&
             sh /app/start-broker.sh"
    ports:
      - "5555:5555"  # ZMQ 브로커 포트
    volumes:
      - ./brokerserver.py:/app/brokerserver.py
      - ./start-broker.sh:/app/start-broker.sh
      - ./requirements.txt:/app/requirements.txt
      # 시스템 시간대 파일 마운트 (추가 안정성)
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    working_dir: /app
    environment:
      - PYTHONUNBUFFERED=1
      # 한국 시간대 설정
      - TZ=Asia/Seoul
    restart: always

volumes:
  postgres_data:
