FROM python:3.9-slim

WORKDIR /app

# 필요한 패키지 설치
RUN pip install pyzmq python-systemd

# 브로커 서버 파일 복사
COPY brokerserver.py .

# 포트 노출
EXPOSE 5555

# 브로커 서버 실행
CMD ["python", "brokerserver.py"] 